import {
  pgTable,
  text,
  integer,
  timestamp,
  boolean,
  uniqueIndex,
  jsonb,
  real
} from 'drizzle-orm/pg-core';

export const employees = pgTable('employees', {
  id: text('id').primaryKey(),
  code: text('code'),
  nameAr: text('name_ar').notNull(),
  nameEn: text('name_en').notNull(),
  avatar: text('avatar'),
  email: text('email'),
  phone: text('phone'),
  department: text('department'),
  jobTitleAr: text('job_title_ar'),
  jobTitleEn: text('job_title_en'),
  shiftId: text('shift_id'),
  pin: text('pin'),
  role: text('role'),
  joinedDate: text('joined_date'),
  status: text('status'),
  annualLeaveBalance: real('annual_leave_balance'),
  casualLeaveBalance: real('casual_leave_balance'),
  regularLeaveBalance: real('regular_leave_balance'),
  sickLeaveBalance: real('sick_leave_balance'),
  isPhotoRemoved: boolean('is_photo_removed'),
});

export const attendanceRecords = pgTable('attendance_records', {
  id: text('id').primaryKey(),
  employeeId: text('employee_id').notNull(),
  date: text('date').notNull(),
  checkIn: text('check_in'),
  checkOut: text('check_out'),
  breakStart: text('break_start'),
  breakEnd: text('break_end'),
  breaks: jsonb('breaks'),
  totalBreakSeconds: integer('total_break_seconds'),
  location: text('location'),
  deviceInfo: text('device_info'),
  lateMinutes: integer('late_minutes').notNull().default(0),
  lateSeconds: integer('late_seconds'),
  earlyLeaveMinutes: integer('early_leave_minutes').notNull().default(0),
  workHours: real('work_hours').notNull().default(0),
  overtimeHours: real('overtime_hours').notNull().default(0),
  status: text('status').notNull(),
  leaveType: text('leave_type'),
  notes: text('notes'),
  verifiedByFace: boolean('verified_by_face'),
  isExcused: boolean('is_excused'),
  excusedBy: text('excused_by'),
  excusedReason: text('excused_reason'),
  updatedAt: text('updated_at'),
  isExplicitCancelCheckOut: boolean('is_explicit_cancel_check_out'),
});

export const leaveRequests = pgTable('leave_requests', {
  id: text('id').primaryKey(),
  employeeId: text('employee_id').notNull(),
  type: text('type').notNull(),
  startDate: text('start_date').notNull(),
  endDate: text('end_date').notNull(),
  reason: text('reason'),
  status: text('status').notNull(),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at'),
  hours: real('hours'),
  permissionSlot: text('permission_slot'),
  attachmentUrl: text('attachment_url'),
  attachmentName: text('attachment_name'),
  reviewedBy: text('reviewed_by'),
  reviewNotes: text('review_notes'),
});

export const overtimeRequests = pgTable('overtime_requests', {
  id: text('id').primaryKey(),
  employeeId: text('employee_id').notNull(),
  date: text('date').notNull(),
  hours: real('hours').notNull().default(0),
  reason: text('reason'),
  status: text('status').notNull().default('pending'),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at'),
  reviewedBy: text('reviewed_by'),
  reviewNotes: text('review_notes'),
});

export const notifications = pgTable('notifications', {
  id: text('id').primaryKey(),
  recipientId: text('recipient_id').notNull(),
  type: text('type').notNull(),
  title: text('title').notNull(),
  message: text('message').notNull(),
  relatedEmployeeId: text('related_employee_id'),
  relatedLeaveId: text('related_leave_id'),
  relatedOvertimeId: text('related_overtime_id'),
  relatedShiftSwapId: text('related_shift_swap_id'),
  isRead: boolean('is_read').default(false),
  createdAt: text('created_at').notNull(),
  updatedAt: text('updated_at').notNull(),
});
