import { and, eq } from 'drizzle-orm';
import { db } from '../src/db/index.js';
import * as schema from '../src/db/schema.js';
import { sendPushToEmployee } from './fcm.js';

const hasDatabase = () => Boolean(process.env.DATABASE_URL || process.env.SUPABASE_DB_URL);
const pick = (s:any,k:string[]) => { const o:any={}; for (const x of k) if (s?.[x]!==undefined) o[x]=s[x]; return o; };
const ms = (v:any) => { if (typeof v === 'number' && Number.isFinite(v)) return v; if (typeof v === 'string' && /^\d{10,}$/.test(v.trim())) { const n=Number(v.trim()); return Number.isFinite(n)?n:0; } const t=new Date(String(v||'')).getTime(); return Number.isFinite(t)?t:0; };
const stamp = (v:any) => { const t=ms(v); return t?new Date(t).toISOString():new Date().toISOString(); };
const newestStamp = (item:any,syncTime:any) => { const itemTime=ms(item?.updatedAt); return itemTime?stamp(itemTime):''; };
const apiPath = (req:any) => String(req.path || req.url || '').split('?')[0].replace(/\/+$/,'') || '/';
const isDataPath = (req:any) => ['/api/data','/data'].includes(apiPath(req));
const isSyncPath = (req:any) => ['/api/sync','/sync'].includes(apiPath(req));

const tombstoneKey = (kind:string) => `__sync_deleted_ids:${kind}`;
async function getTombstones(kind:string):Promise<Set<string>> { const rows=await db.select().from(schema.settings).where(eq(schema.settings.key,tombstoneKey(kind))); const v=rows[0]?.value; return new Set(Array.isArray(v)?v.map(String):[]); }
async function addTombstones(kind:string,ids:any){ if(!Array.isArray(ids)||!ids.length)return; const key=tombstoneKey(kind); const rows=await db.select().from(schema.settings).where(eq(schema.settings.key,key)); const old=Array.isArray(rows[0]?.value)?rows[0].value.map(String):[]; const next=Array.from(new Set([...old,...ids.map((x:any)=>String(x||'').trim()).filter(Boolean)])).slice(-5000); if(rows[0]) await db.update(schema.settings).set({value:next} as any).where(eq(schema.settings.key,key)); else await db.insert(schema.settings).values({key,value:next} as any); }

async function resolveShiftId(value:any){ const requested=String(value??'').trim(); if(requested){const exact=await db.select().from(schema.shifts).where(eq(schema.shifts.id,requested));if(exact[0])return exact[0].id;} if(!requested||requested==='shift-1'){const standard=await db.select().from(schema.shifts).where(and(eq(schema.shifts.startTime,'09:00'),eq(schema.shifts.endTime,'17:00')));if(standard[0])return standard[0].id;} return requested||null; }
async function upsert(table:any,id:string,values:any,existing:any){ if(!existing)return db.insert(table).values(values as any); const incoming=ms(values.updatedAt),current=ms(existing.updatedAt||existing.createdAt); if(!incoming)return; if(!current||incoming>=current)return db.update(table).set(values as any).where(eq(table.id,id)); }

async function upsertEmployee(e:any,syncTime:any){if(!e?.id)return;const id=String(e.id),v=pick(e,['id','code','nameAr','nameEn','avatar','email','phone','department','jobTitleAr','jobTitleEn','shiftId','pin','role','joinedDate','status','annualLeaveBalance','casualLeaveBalance','regularLeaveBalance','sickLeaveBalance','isPhotoRemoved','updatedAt']);v.shiftId=await resolveShiftId(v.shiftId);v.updatedAt=newestStamp(e,syncTime);const a=await db.select().from(schema.employees).where(eq(schema.employees.id,id));if(!a[0]){await db.insert(schema.employees).values(v as any);return;}await upsert(schema.employees,id,v,a[0]);}
async function upsertAttendance(r:any,syncTime:any,tombs:Set<string>){if(!r?.employeeId||!r?.date)return;const employeeId=String(r.employeeId),date=String(r.date).slice(0,10),v=pick(r,['id','employeeId','date','checkIn','checkOut','breakStart','breakEnd','breaks','totalBreakSeconds','location','deviceInfo','lateMinutes','lateSeconds','earlyLeaveMinutes','workHours','overtimeHours','minusHours','status','leaveType','notes','verifiedByFace','isExcused','excusedBy','excusedReason','updatedAt','isExplicitCancelCheckOut']);if(v.id&&tombs.has(String(v.id)))return;v.employeeId=employeeId;v.date=date;v.updatedAt=newestStamp(r,syncTime);if(!v.updatedAt)return;const a=await db.select().from(schema.attendanceRecords).where(and(eq(schema.attendanceRecords.employeeId,employeeId),eq(schema.attendanceRecords.date,date)));if(!a[0]){await db.insert(schema.attendanceRecords).values(v as any);return;}const incoming=ms(v.updatedAt),current=ms((a[0] as any).updatedAt||(a[0] as any).createdAt);if(current&&incoming<current)return;await db.update(schema.attendanceRecords).set(v as any).where(eq(schema.attendanceRecords.id,(a[0] as any).id));}
async function upsertLeave(r:any,syncTime:any,tombs:Set<string>){if(!r?.id||!r?.employeeId)return;const id=String(r.id);if(tombs.has(id))return;const v=pick(r,['id','employeeId','type','startDate','endDate','reason','status','createdAt','updatedAt','hours','permissionSlot','attachmentUrl','attachmentName','reviewedBy','reviewNotes']);v.updatedAt=newestStamp(r,syncTime);if(!v.updatedAt)return;const a=await db.select().from(schema.leaveRequests).where(eq(schema.leaveRequests.id,id));if(!a[0]){await db.insert(schema.leaveRequests).values(v as any);return;}await upsert(schema.leaveRequests,id,v,a[0]);}
async function upsertOvertime(r:any,syncTime:any){if(!r?.id||!r?.employeeId)return;const id=String(r.id),v=pick(r,['id','employeeId','date','type','durationSeconds','reason','status','reviewedBy','reviewNotes','createdAt','updatedAt']);v.updatedAt=newestStamp(r,syncTime);const a=await db.select().from(schema.overtimeRequests).where(eq(schema.overtimeRequests.id,id));if(!a[0]){await db.insert(schema.overtimeRequests).values(v as any);return;}await upsert(schema.overtimeRequests,id,v,a[0]);}
async function upsertShift(r:any,syncTime:any){if(!r?.id||(!r?.name&&!r?.nameAr&&!r?.nameEn)||!r?.startTime||!r?.endTime)return;const id=String(r.id),v=pick(r,['id','name','nameAr','nameEn','startTime','endTime','durationMinutes','breakMinutes','gracePeriodMinutes','overtimeEnabled','isOvernight','createdAt','updatedAt']);v.name=String(r.name||r.nameEn||r.nameAr||id);v.durationMinutes=Number(v.durationMinutes||480);v.breakMinutes=Number(v.breakMinutes||0);v.gracePeriodMinutes=Number(v.gracePeriodMinutes||0);v.overtimeEnabled=Boolean(v.overtimeEnabled);v.isOvernight=Boolean(v.isOvernight||String(v.startTime)>String(v.endTime));v.updatedAt=newestStamp(r,syncTime);delete v.nameAr;delete v.nameEn;const a=await db.select().from(schema.shifts).where(eq(schema.shifts.id,id));if(!a[0]){await db.insert(schema.shifts).values(v as any);return;}await upsert(schema.shifts,id,v,a[0]);}
async function upsertAssignment(r:any,syncTime:any){if(!r?.id||!r?.employeeId||!r?.scheduleDate)return;const id=String(r.id),v=pick(r,['id','employeeId','scheduleDate','shiftTemplateId','customStartTime','customEndTime','durationMinutes','status','createdAt','updatedAt','version']);v.updatedAt=newestStamp(r,syncTime);const a=await db.select().from(schema.employeeShiftAssignments).where(eq(schema.employeeShiftAssignments.id,id));if(!a[0]){await db.insert(schema.employeeShiftAssignments).values(v as any);return;}await upsert(schema.employeeShiftAssignments,id,v,a[0]);}
async function upsertNotification(r:any,syncTime:any){if(!r?.id||!r?.recipientId)return;const id=String(r.id),v=pick(r,['id','recipientId','type','title','message','relatedEmployeeId','relatedLeaveId','relatedOvertimeId','relatedShiftSwapId','isRead','createdAt','updatedAt']);v.updatedAt=newestStamp(r,syncTime);const a=await db.select().from(schema.notifications).where(eq(schema.notifications.id,id));if(!a[0]){await db.insert(schema.notifications).values(v as any);try{await sendPushToEmployee(String(r.recipientId),String(r.title||'TECH SOURCE'),String(r.message||'لديك إشعار جديد.'),{type:String(r.type||'notification')});}catch(e){console.warn('[FCM] notification push failed',e);}return;}await upsert(schema.notifications,id,v,a[0]);}
function collectionKey(x:any,index:number){if(x?.id!=null)return `id:${String(x.id)}`;if(x?.employeeId!=null&&x?.date!=null)return `employee-date:${String(x.employeeId)}:${String(x.date)}`;if(x?.employeeId!=null&&x?.scheduleDate!=null)return `employee-schedule:${String(x.employeeId)}:${String(x.scheduleDate)}`;return `index:${index}`;}
function mergeCollection(existing:any,incoming:any){const oldItems=Array.isArray(existing)?existing:[],newItems=Array.isArray(incoming)?incoming:[],map=new Map<string,any>();oldItems.forEach((x:any,i:number)=>map.set(collectionKey(x,i),x));newItems.forEach((x:any,i:number)=>{const key=collectionKey(x,i),old=map.get(key);if(!old){map.set(key,x);return;}const incomingTs=ms(x?.updatedAt||x?.createdAt),oldTs=ms(old?.updatedAt||old?.createdAt);if(!incomingTs||!oldTs||incomingTs>=oldTs)map.set(key,x);});return Array.from(map.values());}
async function setting(k:string,v:any,updatedAt?:any){const a=await db.select().from(schema.settings).where(eq(schema.settings.key,k)),isCollection=k==='dailyShiftAssignments'||k==='shiftSwapRequests';if(!a[0]){await db.insert(schema.settings).values({key:k,value:v} as any);return;}const stampKey=`__sync_updated_at:${k}`,ts=ms(updatedAt);if(isCollection){await db.update(schema.settings).set({value:mergeCollection(a[0].value,v)} as any).where(eq(schema.settings.key,k));return;}if(!ts)return;const t=await db.select().from(schema.settings).where(eq(schema.settings.key,stampKey)),current=ms(t[0]?.value);if(current&&ts<current)return;await db.update(schema.settings).set({value:v} as any).where(eq(schema.settings.key,stampKey));}
async function del(t:any,ids:any,kind:string){if(!Array.isArray(ids))return;const clean=ids.map((x:any)=>String(x||'').trim()).filter(Boolean);if(!clean.length)return;await addTombstones(kind,clean);for(const id of clean)await db.delete(t).where(eq(t.id,id));}
async function snapshot(){const [employees,attendanceRecords,leaveRequests,overtimeRequests,shifts,settings,employeeShiftAssignments]=await Promise.all([db.select().from(schema.employees),db.select().from(schema.attendanceRecords),db.select().from(schema.leaveRequests),db.select().from(schema.overtimeRequests),db.select().from(schema.shifts),db.select().from(schema.settings),db.select().from(schema.employeeShiftAssignments)]);const m=new Map(settings.filter((s:any)=>!String(s.key).startsWith('__sync_updated_at:')&&!String(s.key).startsWith('__sync_deleted_ids:')).map((s:any)=>[s.key,s.value]));const rawTemplates=m.get('shiftTemplates');const templateValue=Array.isArray(rawTemplates)&&rawTemplates.length===1&&rawTemplates[0]&&typeof rawTemplates[0]==='object'&&rawTemplates[0].value?rawTemplates[0].value:rawTemplates;const effectiveShifts=shifts.length?shifts:((Array.isArray(templateValue)?templateValue:[]).map((x:any)=>({...x,name:String(x?.name||x?.nameEn||x?.nameAr||x?.id||''),durationMinutes:Number(x?.durationMinutes||480),gracePeriodMinutes:Number(x?.gracePeriodMinutes||0)})));const shiftIds=new Set(effectiveShifts.map((s:any)=>String(s.id)));const fallbackShift=effectiveShifts[0]?.id||null;const normalizedEmployees=employees.map((e:any)=>({...e,shiftId:(e.shiftId&&shiftIds.has(String(e.shiftId)))?e.shiftId:fallbackShift}));const all=[...employees,...attendanceRecords,...leaveRequests,...overtimeRequests,...shifts,...employeeShiftAssignments];const lastUpdated=Math.max(0,...all.map((x:any)=>ms(x?.updatedAt||x?.createdAt)));return{success:true,employees:normalizedEmployees,attendanceRecords,leaveRequests,overtimeRequests,shifts:effectiveShifts,dailyShiftAssignments:Array.isArray(m.get('dailyShiftAssignments'))?m.get('dailyShiftAssignments'):[],shiftSwapRequests:Array.isArray(m.get('shiftSwapRequests'))?m.get('shiftSwapRequests'):[],companyNameAr:m.get('companyNameAr')??null,companyNameEn:m.get('companyNameEn')??null,urgentNotice:m.get('urgentNotice')??null,employeeShiftAssignments,lastUpdated};}

export function registerDeviceSyncV2(app:any){app.use(async(req:any,res:any,next:any)=>{if(!hasDatabase())return next();if(req.method!=='GET'&&req.method!=='POST')return next();const dataPath=isDataPath(req),syncPath=isSyncPath(req);if(!dataPath&&!syncPath)return next();res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, proxy-revalidate');res.setHeader('Pragma','no-cache');res.setHeader('Expires','0');try{if(req.method==='GET'&&dataPath)return res.json(await snapshot());if(req.method!=='POST'||!syncPath)return next();const b=req.body||{},has=['employees','attendanceRecords','leaveRequests','overtimeRequests','shifts','employeeShiftAssignments','dailyShiftAssignments','shiftSwapRequests','companyNameAr','companyNameEn','urgentNotice','deletedAttendanceIds','deletedEmployeeIds','deletedLeaveIds'].some(k=>b[k]!==undefined);if(!has)return res.json(await snapshot());const syncTime=stamp(b.lastUpdated||Date.now());const attendanceTombs=await getTombstones('attendance'),leaveTombs=await getTombstones('leave');for(const e of Array.isArray(b.employees)?b.employees:[])await upsertEmployee(e,syncTime);for(const r of Array.isArray(b.attendanceRecords)?b.attendanceRecords:[])await upsertAttendance(r,syncTime,attendanceTombs);for(const r of Array.isArray(b.leaveRequests)?b.leaveRequests:[])await upsertLeave(r,syncTime,leaveTombs);for(const r of Array.isArray(b.overtimeRequests)?b.overtimeRequests:[])await upsertOvertime(r,syncTime);for(const s of Array.isArray(b.shifts)?b.shifts:[])await upsertShift(s,syncTime);for(const a of Array.isArray(b.employeeShiftAssignments)?b.employeeShiftAssignments:[])await upsertAssignment(a,syncTime);if(Array.isArray(b.dailyShiftAssignments))await setting('dailyShiftAssignments',b.dailyShiftAssignments,syncTime);if(Array.isArray(b.shiftSwapRequests))await setting('shiftSwapRequests',b.shiftSwapRequests,syncTime);if(b.companyNameAr!==undefined)await setting('companyNameAr',b.companyNameAr,syncTime);if(b.companyNameEn!==undefined)await setting('companyNameEn',b.companyNameEn,syncTime);if(b.urgentNotice!==undefined)await setting('urgentNotice',b.urgentNotice,syncTime);await del(schema.attendanceRecords,b.deletedAttendanceIds,'attendance');await del(schema.employees,b.deletedEmployeeIds,'employee');await del(schema.leaveRequests,b.deletedLeaveIds,'leave');return res.json(await snapshot());}catch(e){console.error('[device-sync-v2]',e);return res.status(500).json({success:false,error:'Cross-device sync failed'});}});}
