import type { Express } from 'express';
import { sql } from 'drizzle-orm';
import { db } from '../src/db/index.js';
import * as schema from '../src/db/schema.js';
import { getApps, cert, initializeApp } from 'firebase-admin/app';
import { getMessaging } from 'firebase-admin/messaging';
function adminMessaging(){if(!process.env.FIREBASE_SERVICE_ACCOUNT_JSON)return null;try{if(!getApps().length)initializeApp({credential:cert(JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON))});return getMessaging();}catch(e){console.error('[FCM] init failed',e);return null;}}
async function tokensFor(employeeId:string){if(!process.env.SUPABASE_DB_URL)return [];try{const rows=await db.select().from(schema.settings).where(sql`key = 'fcm_tokens'`).limit(1);const v:any=rows[0]?.value;return(Array.isArray(v)?v:[]).filter((x:any)=>x?.employeeId===employeeId).map((x:any)=>x.token).filter(Boolean);}catch{return[];}}
async function saveToken(employeeId:string,token:string,platform:string){if(!process.env.SUPABASE_DB_URL)return;const rows=await db.select().from(schema.settings).where(sql`key = 'fcm_tokens'`).limit(1);const current:any[]=Array.isArray(rows[0]?.value)?rows[0].value as any[]:[];const next=current.filter((x:any)=>x?.token!==token);next.push({employeeId,token,platform,updatedAt:new Date().toISOString()});await db.insert(schema.settings).values({key:'fcm_tokens',value:next}).onConflictDoUpdate({target:schema.settings.key,set:{value:next}});}
export async function sendPushToEmployee(employeeId:string,title:string,body:string,data:Record<string,string>={}){const m=adminMessaging();if(!m)return{sent:0,configured:false};const tokens=await tokensFor(employeeId);if(!tokens.length)return{sent:0,configured:true};const r=await m.sendEachForMulticast({tokens,notification:{title,body},data});return{sent:r.successCount,configured:true};}
export function registerFcmRoutes(app:Express){app.post('/api/push/register',async(req,res)=>{try{const{employeeId,token,platform='unknown'}=req.body||{};if(!employeeId||!token)return res.status(400).json({success:false});await saveToken(String(employeeId),String(token),String(platform));res.json({success:true});}catch(e){console.error('[FCM] register',e);res.status(500).json({success:false});}});app.post('/api/push/send',async(req,res)=>{try{const{employeeId,title,body,data={}}=req.body||{};if(!employeeId||!title||!body)return res.status(400).json({success:false});res.json({success:true,...await sendPushToEmployee(String(employeeId),String(title),String(body),data)});}catch(e){console.error('[FCM] send',e);res.status(500).json({success:false});}});}
