const fs = require('fs');

const path = 'src/components/WeeklyShiftSchedule.tsx';
let s = fs.readFileSync(path, 'utf8');

if (!s.includes('selectedEmployeeIds')) {
  s = s.replace(
    "const [selectedEmployeeId, setSelectedEmployeeId] = useState(suppliedUser?.id || suppliedEmployees?.[0]?.id || '');",
    "const [selectedEmployeeId, setSelectedEmployeeId] = useState(suppliedUser?.id || suppliedEmployees?.[0]?.id || '');\n  const [selectedEmployeeIds, setSelectedEmployeeIds] = useState<string[]>([]);"
  );
}

if (!s.includes('applyScheduleToSelectedEmployees')) {
  const marker = "  const saveWeek = async () => {";
  const helper = `  const applyScheduleToSelectedEmployees = async () => {\n    if (!isLeader || selectedEmployeeIds.length === 0 || !days.length) return;\n    setError(null);\n    const updatedAt = new Date().toISOString();\n    let next = [...assignments];\n\n    for (const employeeId of selectedEmployeeIds) {\n      for (const day of days) {\n        const draftValue = Object.prototype.hasOwnProperty.call(draft, day.key) ? draft[day.key] : undefined;\n        const source = assignmentFor(employee?.id || '', day.key);\n        const isOffDay = draftValue !== undefined ? draftValue === OFF_DAY_SHIFT_ID : Boolean(source?.isOffDay);\n        const shiftId = isOffDay ? '' : (draftValue !== undefined ? draftValue : source?.shiftId || '');\n        const index = next.findIndex(a => a.employeeId === employeeId && a.date === day.key);\n        if (!shiftId && !isOffDay) {\n          if (index >= 0) next.splice(index, 1);\n          continue;\n        }\n        const assignment: DailyShiftAssignment = { employeeId, date: day.key, shiftId, isOffDay, assignedBy: currentUser?.id, updatedAt };\n        if (index >= 0) next[index] = assignment;\n        else next.push(assignment);\n        onSaveDailyShift?.(assignment);\n      }\n    }\n\n    setAssignments(next);\n    localStorage.setItem('daily_shift_assignments', JSON.stringify(next));\n    try {\n      const response = await fetch('/api/sync', {\n        method: 'POST',\n        headers: { 'Content-Type': 'application/json' },\n        body: JSON.stringify({ dailyShiftAssignments: next }),\n      });\n      if (!response.ok) throw new Error('sync failed');\n      setSavedAt(new Date().toLocaleTimeString(lang === 'ar' ? 'ar-EG' : 'en-US', { hour: '2-digit', minute: '2-digit' }));\n      setSelectedEmployeeIds([]);\n    } catch {\n      setError(lang === 'ar' ? 'تم الحفظ محليًا لكن تعذر المزامنة.' : 'Saved locally, but server sync failed.');\n    }\n  };\n\n`;
  if (!s.includes(marker)) throw new Error('saveWeek marker not found');
  s = s.replace(marker, helper + marker);
}

const employeeSelect = "          {isLeader && <label className=\"text-xs font-black text-slate-700 block max-w-xl\"><span className=\"flex items-center gap-1.5 mb-1.5\"><Users className=\"w-3.5 h-3.5\" />{lang === 'ar' ? 'الموظف' : 'Employee'}</span><select value={employee?.id || ''} onChange={e => { setSelectedEmployeeId(e.target.value); setDraft({}); setSavedAt(null); }} className=\"w-full min-h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm font-bold text-slate-900\">{visibleEmployees.map(e => <option key={e.id} value={e.id}>{e.code} - {lang === 'ar' ? e.nameAr : e.nameEn}</option>)}</select></label>}";

if (s.includes(employeeSelect) && !s.includes('Apply to Selected')) {
  const replacement = `${employeeSelect}\n\n          {isLeader && (\n            <div className=\"rounded-2xl border border-emerald-200 bg-emerald-50/60 p-3 sm:p-4 space-y-3\">\n              <div className=\"flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2\">\n                <div>\n                  <div className=\"text-xs font-black text-slate-900\">{lang === 'ar' ? 'تطبيق الجدول على عدة موظفين' : 'Apply Schedule to Multiple Employees'}</div>\n                  <div className=\"text-[10px] text-slate-500 mt-1\">{lang === 'ar' ? 'حدد الموظفين ثم سيتم نسخ نفس جدول الأسبوع والبريكات الخاصة بكل شفت.' : 'Select employees to copy the same weekly schedule and each shift’s own breaks.'}</div>\n                </div>\n                <div className=\"flex gap-2\">\n                  <button type=\"button\" onClick={() => setSelectedEmployeeIds(visibleEmployees.map(e => e.id))} className=\"px-3 py-2 rounded-lg bg-white border border-slate-200 text-[10px] font-black\">{lang === 'ar' ? 'تحديد الكل' : 'Select All'}</button>\n                  <button type=\"button\" onClick={() => setSelectedEmployeeIds([])} className=\"px-3 py-2 rounded-lg bg-white border border-slate-200 text-[10px] font-black\">{lang === 'ar' ? 'إلغاء' : 'Clear'}</button>\n                </div>\n              </div>\n              <div className=\"grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2 max-h-48 overflow-y-auto pr-1\">\n                {visibleEmployees.map(e => (\n                  <label key={e.id} className=\"flex items-center gap-2 rounded-xl bg-white border border-slate-200 px-3 py-2 cursor-pointer\">\n                    <input type=\"checkbox\" checked={selectedEmployeeIds.includes(e.id)} onChange={ev => setSelectedEmployeeIds(prev => ev.target.checked ? [...new Set([...prev, e.id])] : prev.filter(id => id !== e.id))} className=\"h-4 w-4 rounded border-slate-300 text-emerald-600 focus:ring-emerald-500\" />\n                    <span className=\"text-xs font-bold text-slate-800 truncate\">{e.code} - {lang === 'ar' ? e.nameAr : e.nameEn}</span>\n                  </label>\n                ))}\n              </div>\n              <button type=\"button\" disabled={!selectedEmployeeIds.length} onClick={applyScheduleToSelectedEmployees} className=\"w-full min-h-11 rounded-xl bg-emerald-600 hover:bg-emerald-700 disabled:opacity-50 disabled:cursor-not-allowed text-white text-xs font-black\">{lang === 'ar' ? `تطبيق الجدول على ${selectedEmployeeIds.length} موظف` : `Apply Schedule to ${selectedEmployeeIds.length} Selected Employees`}</button>\n            </div>\n          )}`;
  s = s.replace(employeeSelect, replacement);
}

fs.writeFileSync(path, s);
console.log('Bulk schedule patch applied');
