const fs = require('fs');

function patch(path, marker, fn) {
  let code = fs.readFileSync(path, 'utf8');
  if (code.includes(marker)) return false;
  code = fn(code);
  if (!code.includes(marker)) throw new Error(`${path}: marker not inserted`);
  fs.writeFileSync(path, code, 'utf8');
  return true;
}

patch('src/App.tsx', '/* PERSISTENCE_V2_NORMALIZATION */', (code) => {
  const anchor = '/* =========================================================\n     CENTRAL SERVER PULL\n     ========================================================= */';
  const helpers = `/* PERSISTENCE_V2_NORMALIZATION */\nfunction normalizeLeaveFromServer(item: any): LeaveRequest {\n  return { ...item, id: String(item?.id ?? '').trim(), employeeId: String(item?.employeeId ?? item?.employee_id ?? '').trim(), startDate: String(item?.startDate ?? item?.start_date ?? '').slice(0, 10), endDate: String(item?.endDate ?? item?.end_date ?? item?.startDate ?? item?.start_date ?? '').slice(0, 10), status: item?.status ?? 'pending', createdAt: item?.createdAt ?? item?.created_at ?? new Date().toISOString(), updatedAt: item?.updatedAt ?? item?.updated_at ?? item?.createdAt ?? item?.created_at ?? new Date().toISOString() } as LeaveRequest;\n}\nfunction normalizeAssignmentFromServer(item: any): DailyShiftAssignment {\n  const shiftId = String(item?.shiftId ?? item?.shift_id ?? '').trim();\n  const rawOff = item?.isOffDay ?? item?.is_off_day ?? String(item?.status ?? '').toUpperCase() === 'OFF';\n  const isOffDay = shiftId ? false : (rawOff === true || rawOff === 1 || String(rawOff).toLowerCase() === 'true' || String(rawOff).toLowerCase() === '1' || String(rawOff).toLowerCase() === 'off');\n  return { ...item, employeeId: String(item?.employeeId ?? item?.employee_id ?? '').trim(), date: String(item?.date ?? item?.scheduleDate ?? item?.schedule_date ?? '').slice(0, 10), shiftId: isOffDay ? '' : shiftId, isOffDay, assignedBy: item?.assignedBy ?? item?.assigned_by, updatedAt: item?.updatedAt ?? item?.updated_at } as DailyShiftAssignment;\n}\nfunction mergePersistentLeaves(local: LeaveRequest[] = [], incoming: LeaveRequest[] = []): LeaveRequest[] {\n  const server = (Array.isArray(incoming) ? incoming : []).map(normalizeLeaveFromServer).filter(x => x.id);\n  const map = new Map<string, LeaveRequest>(server.map(x => [x.id, x]));\n  const now = Date.now();\n  for (const raw of Array.isArray(local) ? local : []) { const item = normalizeLeaveFromServer(raw); if (!item.id || map.has(item.id)) continue; const stamp = Date.parse(String(item.updatedAt || item.createdAt || '')); if (!Number.isFinite(stamp) || now - stamp <= 14 * 24 * 60 * 60 * 1000) map.set(item.id, item); }\n  return Array.from(map.values());\n}\nfunction mergePersistentSchedule(local: DailyShiftAssignment[] = [], incoming: DailyShiftAssignment[] = []): DailyShiftAssignment[] {\n  const server = (Array.isArray(incoming) ? incoming : []).map(normalizeAssignmentFromServer).filter(x => x.employeeId && /^\\d{4}-\\d{2}-\\d{2}$/.test(x.date));\n  const localRows = (Array.isArray(local) ? local : []).map(normalizeAssignmentFromServer).filter(x => x.employeeId && /^\\d{4}-\\d{2}-\\d{2}$/.test(x.date));\n  if (!server.length) return localRows;\n  const map = new Map<string, DailyShiftAssignment>();\n  for (const row of localRows) map.set(row.employeeId + '|' + row.date, row);\n  for (const row of server) map.set(row.employeeId + '|' + row.date, row);\n  return Array.from(map.values());\n}\n\n`;
  const pos = code.indexOf(anchor);
  if (pos < 0) throw new Error('App central pull anchor not found');
  code = code.slice(0, pos) + helpers + code.slice(pos);

  code = code.replace(
    /if \(Array\.isArray\(data\.dailyShiftAssignments\)\) \{[\s\S]*?if \(Array\.isArray\(data\.shifts\)\) \{\s*setShifts\(data\.shifts\);\s*try \{\s*localStorage\.setItem\(\s*'attendance_shifts',\s*JSON\.stringify\(data\.shifts\)\s*\);\s*\} catch \{\}/,
    `if (Array.isArray(data.dailyShiftAssignments)) {\n            const stableAssignments = mergePersistentSchedule(dailyShiftAssignments, data.dailyShiftAssignments);\n            setDailyShiftAssignments(stableAssignments);\n            try { localStorage.setItem('daily_shift_assignments', JSON.stringify(stableAssignments)); } catch {}\n          }\n          if (Array.isArray(data.shifts)) {\n            setShifts(data.shifts);\n            try { localStorage.setItem('attendance_shifts', JSON.stringify(data.shifts)); } catch {}`
  );
  code = code.replace(/const serverLeaves =\s*applyPendingLeaveDecisions\(\s*data\.leaveRequests\s*\);/g, `const serverLeaves = applyPendingLeaveDecisions(mergePersistentLeaves(leaveRequestsRef.current || leaveRequests, data.leaveRequests));`);
  return code;
});

patch('src/components/WeeklyShiftSchedule.tsx', '/* PERSISTENCE_V2_WEEKLY_FETCH */', (code) => {
  const start = code.indexOf('  useEffect(() => {\n    let cancelled = false;\n    const load = async () => {');
  const end = code.indexOf('\n  const visibleEmployees = useMemo', start);
  if (start < 0 || end < 0) throw new Error('Weekly schedule load effect not found');
  const replacement = `  /* PERSISTENCE_V2_WEEKLY_FETCH */\n  useEffect(() => {\n    let cancelled = false;\n    const load = async () => {\n      try {\n        const storedUser = localStorage.getItem('logged_in_user');\n        if (!suppliedUser && storedUser) { const parsed = JSON.parse(storedUser) as Employee; if (parsed?.id && parsed.status !== 'inactive' && !cancelled) { setCurrentUser(parsed); setSelectedEmployeeId(parsed.id); } }\n        const response = await fetch('/api/data?_=' + Date.now(), { method:'GET', credentials:'include', cache:'no-store', headers:{'Cache-Control':'no-cache','Pragma':'no-cache','Accept':'application/json'} });\n        if (!response.ok) throw new Error('Server data fetch failed: ' + response.status);\n        const data = await response.json();\n        if (cancelled || !data || data.success === false) return;\n        if (Array.isArray(data.employees) && data.employees.length) setEmployees(data.employees);\n        if (Array.isArray(data.shifts) && data.shifts.length) setShifts(data.shifts);\n        if (Array.isArray(data.dailyShiftAssignments)) {\n          const normalize = (item:any):DailyShiftAssignment => { const shiftId=String(item?.shiftId ?? item?.shift_id ?? '').trim(); const rawOff=item?.isOffDay ?? item?.is_off_day ?? String(item?.status ?? '').toUpperCase()==='OFF'; const isOffDay=shiftId ? false : (rawOff===true || rawOff===1 || String(rawOff).toLowerCase()==='true' || String(rawOff).toLowerCase()==='1' || String(rawOff).toLowerCase()==='off'); return {...item,employeeId:String(item?.employeeId ?? item?.employee_id ?? '').trim(),date:String(item?.date ?? item?.scheduleDate ?? item?.schedule_date ?? '').slice(0,10),shiftId:isOffDay?'':shiftId,isOffDay}; };\n          const incoming=data.dailyShiftAssignments.map(normalize).filter((x:any)=>x.employeeId && /^\\d{4}-\\d{2}-\\d{2}$/.test(x.date));\n          const stored=localStorage.getItem('daily_shift_assignments'); const local=stored ? (()=>{try{return JSON.parse(stored).map(normalize);}catch{return [];}})() : [];\n          const map=new Map<string,DailyShiftAssignment>(); for(const row of local) if(row?.employeeId&&row?.date) map.set(row.employeeId+'|'+row.date,row); for(const row of incoming) map.set(row.employeeId+'|'+row.date,row);\n          const merged=Array.from(map.values()); setAssignments(merged); localStorage.setItem('daily_shift_assignments',JSON.stringify(merged));\n        }\n      } catch (err) { console.error('Failed to load weekly schedule', err); }\n      finally { if (!cancelled) setLoading(false); }\n    };\n    setLoading(true); void load(); return () => { cancelled = true; };\n  }, [suppliedUser]);\n`;
  return code.slice(0,start) + replacement + code.slice(end);
});

console.log('[patch_persistence_v2] applied');
